name: Test
run-name: Test
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'entrada - salida'

jobs:
  time-register:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout time-register
      uses: actions/checkout@v4

    - name: Send Whatsapp Msg Success
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.callmebot.com/whatsapp.php?phone=34680509643&text=Fichaje+realizado+correctamente&apikey=8589500'
        method: 'GET'
