name: Time register
run-name: Time register
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "entrada - salida"

jobs:
  time-register:
    runs-on: ubuntu-latest
    env:
      POL_USER: ${{ secrets.POL_USER }}
    steps:
      - name: Checkout time-register
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Update apt-get
        run: sudo apt-get update

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get install -y \
            libasound2 \
            libicu-dev \
            libffi-dev \
            libx264-dev
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test navigation.spec.js --grep ${{ inputs.tag }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+02:00"

      - name: Send email notification
        uses: cinotify/github-action@main
        with:
          to: "${{ secrets.POL_EMAIL }}"
          subject: "Fichaje ${{ inputs.tag }} - ${{ steps.current-time.outputs.day }}/${{ steps.current-time.outputs.month }}/${{ steps.current-time.outputs.year }} - ${{ steps.current-time.outputs.hour }}:${{ steps.current-time.outputs.minute }}"
          body: "Fichaje realizado correctamente."
          attachment: "screenshot.png"

      - name: Send Whatsapp Msg Success
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.callmebot.com/whatsapp.php?phone=${{ secrets.POL_PHONE }}&text=Fichaje+realizado+correctamente&apikey=${{ secrets.POL_WHATS_APIKEY }}"
          method: "GET"

      - name: Send Whatsapp Msg If Error
        if: failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.callmebot.com/whatsapp.php?phone=${{ secrets.POL_PHONE }}&text=ERROR+fichaje&apikey=${{ secrets.POL_WHATS_APIKEY }}"
          method: "GET"
